---
Name: locketroutes
After:
  - '#rootroutes'
  - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    'user//$Action/$ID': 'AndrewAndante\Locket\Controllers\InviteController'
    'gallery/$ID': 'AndrewAndante\Locket\Controllers\GalleryController'
    '': 'AndrewAndante\Locket\Controllers\HomeController'