---
Name: locketroutes
After: framework/routes#coreroutes
---
SilverStripe\Control\Director:
  rules:
    'gallery/$ID': 'AndrewAndante\Locket\Controllers\GalleryController'
    '': 'AndrewAndante\Locket\Controllers\HomeController'